// ========================================
// PALAVRAS NEGATIVAS (MOVIDAS DO SETUP)
// ========================================

export const NEGATIVE_KEYWORDS_PHYSICAL = `Grátis, grátis, gratis, grats, gráts, grafis, de graça, de graca, gratuito, gratuto, gratuita, gratuta, gratuitos, gratuitas, gratutos, gratutas, 
mercado livre, baixar, download, donload, pdf, pedf, pirata, torrente, tnt, crack, torrent, thepiratebay, rarbg, crackeado, free, 800, 
sem investir, sem gastar, gastar nada, presencial, baixaki, superdownload, baixar, de graça, google drive, vsl delay, usar, uso, usuário, 
farmacia, farmácia, telefone, contato, numero, endereço, correio, entrega, prazo, frete, afiliados, homart afiliados, hotmart afiliados, 
hotmart afiliado, monetizze, eduzz, montezze afiliados, eduzz afiliados, apostila, 4shared, certificado, diploma, sexo, texto, netlfix, 
amazon, resenha, filme, assitir, livro, em, gratiz, grátiz, grêtiz, "em", farmacia, "como funciona", "sera que funciona", caseiras, 
caseirense, caseirismo, caseiro, caseiros, associação, casos de estudo, guia, associação, jornal, revista, métricas, notícias, investigação, 
review, opinião, estatísticas, histórias, tutorial, definição, significado, sobre, relatorios, imagens, fotografias, fotos, fotografias, 
especificações, gratis, gratuito, amostras, leilão, passatempo, revenda, segunda mão, usado, sobre, definição, comparação, diagrama de, 
exemplo, exemplos, história, mapas, amostra, amostras, quais são, o que é, Português, pior, queixa, reclamação, fraude, crime, escândalo, 
negativo, Apoio ao cliente, Inglês, worst, complaint, complaint, fraud, crime, scandal, negative, classe, aulas, da faculdade, faculdades, 
de cursos, de cursos, de educação, estudar, escolas, de formação, universidades, universitário, magazine luiza, magalu, ponto frio, 
ricardo eletro, walmart, colombo, gremio, inter, são paulo, flamengo, criciuma, cruzeio, santos, vasco, botafogo, parana, atletico, 
mineiro, gaucho, parense, corinthians, palmeiras, vila nova, ceara, blog, youtube, facebook, instagram, idade, namorada, namorado, 
escandalo, nude, video, caiu na net, fuxico, fofocando, aniversario, signo, mês, crush, em, [mam onde fica], [mam onde comprar no brasil], 
mam onde vende, onde, em, no, como funciona, funciona, formula, composição, [one punch man], [onde comprar mam mais barato], 
[onde comprar mam], [onde comprar mam em bh], [onde fica o mam em salvador], [porque mam], [porque te hice mal], [por que el amor mam], 
[porque mi mamá], [porque huele mal], [porque iron man], [sao mam], [mam sao paulo], [mam sao paulo exposicoes], [mam sao paulo horario], 
[mam sao paulo exposicao], [mam são paulo acervo], acervo, museu, instituição, vara, casa, loja, empresa, industria, restaurante, 
tettarelle, cambiare, mamá, mal, iron, [mamadeira mam é boa], boa, bpa, anticolica, ingles, importada, mamadeira, quem, tomar, mamao, 
esterilizar, revender, significa, cursos, memebership, parking, orgazm, bebe, bebê, beber, recem nascido, meme, content, beach, miami, 
mam-e, avent, mdm, magazine, moc, nuk, creche, madam, wild, mma, francisco morato, bottle, filtros, flamengo, magazine luiza, magalu, 
ponto frio, ricardo eletro, walmart, colombo, gremio, inter, são paulo, flamengo, criciuma, cruzeio, santos, vasco, botafogo, parana, 
atletico, mineiro, gaucho, parense, corinthians, palmeiras, vila nova, ceara, festas, flex, fashion, salvador, start, significado, 
margarida, store, start 0-2, kin, kpop, kalunga, killa, knows best, tradução, trabalhe conosco, tour virtual, telefone, talent, tgx, 
tietê, tradutor, aromas, air, arquitetura, horario, horario de funcionamento, bilheteria, bomboniere, air night, aterro do flamengo, 
arquiteto, yoja, yoka, perfect 6+, pneus, programação, plastic, piscinas, perfect start, obras, odontologia, queen, quarta feira de cinzas, 
quailman, quotes, aquaman, quimper, bico 1, silicone, usp, ultivent, usa, united, utd, united x, utd x, vagas, vinhedo, food, wild, vector, 
distribuidora, janeiro, fevereiro, março, abril, maio, junho, julho, agosto, setembro, outubro, novembro, dezembro`;

export const NEGATIVE_KEYWORDS_DIGITAL = `Grátis, grátis, gratis, grats, gráts, grafis, "de graça", "de graca", gratuito, gratuto, gratuita, gratuta, 
gratuitos, gratuitas, gratutos, gratutas, "mercado livre", baixar, download, donload, pdf, pedf, pirata, torrente, tnt, crack, torrent, 
thepiratebay, rarbg, crackeado, free, 800, "sem investir", "sem gastar", "gastar nada", "presencial", baixaki, superdownload, baixar, 
"de graça", "google drive", vsl delay, drive, afiliados, "homart afiliados", "hotmart afiliados", "hotmart afiliado, monetizze, eduzz, 
"montezze afiliados", "eduzz afiliados", apostila, 4shared, sexo, netlfix, amazon, filme, assitir, livro, gratiz, grátiz, grêtiz, Login, 
login, logim, loguin, entrar, senac, sesi, acessar, acesso, acessa, acesse, "área do aluno", "area do aluno", "área de membros", 
"area de membros ", membros, portal, aluno, aluna, alunos, alunas, club, presencial, cidade, sebare, sebraei, sebrae, sesi, senac, senak, 
monetizze, eduz, cancelar, reclame aqui, png, jpeg, wallpaper, imagem, Rio Branco, Maceió, Macapá, Manaus, Salvador, Fortaleza, Brasília, 
Vitória, Goiânia, São Luís, Cuiabá, Campo Grande, Belo Horizonte, Belém, João Pessoa, Curitiba, Recife, Teresina, Rio de Janeiro, Natal, 
Porto Alegre, Porto Velho, Boa Vista, Florianópolis, São Paulo, Aracaju, Palmas, png, jpeg, avi, mp4, presencial, acesso, area membros, 
https, login, instagram, facebook, youtube, anos, aniversário, filhos, mãe, pai, namorada, tio, cidade, mora, zero, idade, cpf, genero, 
endereço, avaliações, nota, reclame, aqui, "é bom", reembolso, extorno, casa, bairro, apartamento, ap, ape, kitinete, quitinete, cama, 
armário, tv, televisão, radio, celular, reclamação, reclamações, procon, reembolso, extorno, volta, dinheiro, telegran, telegram, email, 
contato, telefone, fone, sexo, endereço, download, material, club, afiliados, suporte, reclamacao, reclamações, .com.br, funciona, entrar, 
"de graça", acessar, cancelar, "reclame aqui", "qual o melhor", "é bom", "canal youtube", "como acessar", gratis, grátis, gratuito, pdf, 
http, dowload, login, sobre, acesso, afiliado, presencial, sebrae, "mercado livre, senac, com.br, existe, baixar, google drive, acesse, 
é bom, "material de divulgação", instagran, free, medium, idade, "quantos anos", biografia, wikipedia, aluno, "area de membros", área, 
membros, youtube, reclame, alunos, torrent, pubase, loguim, dowload, reembolso, reclame aqui, contato, telefone, "o que é", live, afiliação, sparkle`;

export const NEGATIVE_KEYWORDS_INTL = `free, login, sign in, download, pdf, torrent, crack, hack, review, scam, fake, complaints, support, contact, 
phone number, address, customer service, refund, money back, free trial, cheap, discount code, coupon, jobs, careers, salary, hiring, 
internship, wiki, wikipedia, youtube, video, tutorial, how to, what is, meaning, definition, examples, samples, used, second hand, ebay, 
amazon, walmart, target, best buy, craigslist, facebook, instagram, twitter, tiktok, reddit, forum, blog, news, article, story`;